export const searchablePages = [
  {
    titleKey: "searchPages.discover.title",
    subtitleKey: "searchPages.discover.subtitle",
    path: "/discover",
    icon: "rocket",
    keywords: [
      "discover",
      "descobrir",
      "curiosidades",
      "missões",
      "missions",
      "exploradores",
      "explorers",
      "universo",
      "universe",
    ],
  },
  {
    titleKey: "searchPages.quiz.title",
    subtitleKey: "searchPages.quiz.subtitle",
    path: "/quiz",
    icon: "help",
    keywords: [
      "quiz",
      "questionário",
      "teste",
      "test",
      "jogo",
      "game",
      "conhecimentos",
      "knowledge",
    ],
  },
  {
    titleKey: "searchPages.spaceWeather.title",
    subtitleKey: "searchPages.spaceWeather.subtitle",
    path: "/donki",
    icon: "sun",
    keywords: [
      "donki",
      "space weather",
      "solar",
      "storm",
      "sun",
      "sol",
      "meteorologia espacial",
      "clima espacial",
      "meteorologia",
      "tempestade",
      "erupção",
      "flare",
    ],
  },
  {
    titleKey: "searchPages.earth.title",
    subtitleKey: "searchPages.earth.subtitle",
    path: "/epic",
    icon: "globe",
    keywords: [
      "epic",
      "earth",
      "terra",
      "planet",
      "planeta",
      "imagem",
      "image",
      "satélite",
      "satellite",
    ],
  },
  {
    titleKey: "searchPages.asteroids.title",
    subtitleKey: "searchPages.asteroids.subtitle",
    path: "/neowatch",
    icon: "asteroid",
    keywords: [
      "neows",
      "neowatch",
      "asteroids",
      "asteroides",
      "asteróides",
      "asteroid",
      "neo",
      "objetos próximos",
      "near earth",
      "near-earth objects",
    ],
  },
];